//
// Generated By: dol2asm
// Translation Unit: jstudio-object
//

#include "JSystem/JStudio/JStudio/jstudio-object.h"

/* 80285E0C-80285E54 28074C 0048+00 6/6 11/11 0/0 .text __dt__Q37JStudio14TVariableValue7TOutputFv
 */
JStudio::TVariableValue::TOutput::~TOutput() {
    // NONMATCHING
}

/* 80285E54-80285EB8 280794 0064+00 1/1 0/0 0/0 .text
 * update__Q27JStudio14TVariableValueFdPQ27JStudio8TAdaptor     */
void JStudio::TVariableValue::update(f64 param_0, JStudio::TAdaptor* param_1) {
    if (field_0x8) {
        field_0x8(this, param_0);
        JUT_ASSERT(200, pOutput_!=0);
        (*pOutput_)(mValue, param_1);
    }
}

/* 80285EB8-80285ECC 2807F8 0014+00 4/4 4/4 0/0 .text
 * update_immediate___Q27JStudio14TVariableValueFPQ27JStudio14TVariableValued */
void JStudio::TVariableValue::update_immediate_(JStudio::TVariableValue* param_0, f64 param_1) {
    param_0->mValue = param_0->field_0xc.val;
    param_0->field_0x8 = NULL;
}

/* 80285ECC-80285F08 28080C 003C+00 1/1 0/0 0/0 .text
 * update_time___Q27JStudio14TVariableValueFPQ27JStudio14TVariableValued */
void JStudio::TVariableValue::update_time_(JStudio::TVariableValue* param_0, f64 param_1) {
    param_0->mValue = param_0->field_0xc.val * (param_0->field_0x4 * param_1);
}

/* 80285F08-80285F6C 280848 0064+00 2/2 0/0 0/0 .text
 * update_functionValue___Q27JStudio14TVariableValueFPQ27JStudio14TVariableValued */
void JStudio::TVariableValue::update_functionValue_(JStudio::TVariableValue* param_0,
                                                        f64 param_1) {
    param_0->mValue = param_0->field_0xc.fv->getValue(param_0->field_0x4 * param_1);
}

/* 80285F6C-80285FCC 2808AC 0060+00 2/1 0/0 0/0 .text
 * __dt__Q37JStudio14TVariableValue13TOutput_none_Fv            */
JStudio::TVariableValue::TOutput_none_::~TOutput_none_() {
    // NONMATCHING
}

/* 80285FCC-80285FD0 28090C 0004+00 1/0 0/0 0/0 .text
 * __cl__Q37JStudio14TVariableValue13TOutput_none_CFfPQ27JStudio8TAdaptor */
void JStudio::TVariableValue::TOutput_none_::operator()(f32 param_0,
                                                        JStudio::TAdaptor* param_1) const {
    /* empty function */
}

/* 80285FD0-80286018 280910 0048+00 8/8 0/0 0/0 .text            __dt__Q27JStudio8TAdaptorFv */
JStudio::TAdaptor::~TAdaptor() {}

/* 80286018-8028601C 280958 0004+00 8/0 2/0 0/0 .text adaptor_do_prepare__Q27JStudio8TAdaptorFv */
// void JStudio::TAdaptor::adaptor_do_prepare() {
extern "C" void adaptor_do_prepare__Q27JStudio8TAdaptorFv() {
    /* empty function */
}

/* 8028601C-80286020 28095C 0004+00 8/0 4/0 0/0 .text adaptor_do_begin__Q27JStudio8TAdaptorFv */
void JStudio::TAdaptor::adaptor_do_begin() {
    /* empty function */
}

/* 80286020-80286024 280960 0004+00 8/0 2/0 0/0 .text adaptor_do_end__Q27JStudio8TAdaptorFv */
void JStudio::TAdaptor::adaptor_do_end() {
    /* empty function */
}

/* 80286024-80286028 280964 0004+00 8/0 2/0 0/0 .text adaptor_do_update__Q27JStudio8TAdaptorFUl */
void JStudio::TAdaptor::adaptor_do_update(u32 param_0) {
    /* empty function */
}

/* 80286028-8028602C 280968 0004+00 8/0 4/0 0/0 .text
 * adaptor_do_data__Q27JStudio8TAdaptorFPCvUlPCvUl              */
void JStudio::TAdaptor::adaptor_do_data(void const* param_0, u32 param_1, void const* param_2,
                                        u32 param_3) {
    /* empty function */
}

/* 8028602C-802860CC 28096C 00A0+00 8/7 0/0 0/0 .text
 * adaptor_setVariableValue__Q27JStudio8TAdaptorFPQ27JStudio8TControlUlQ37JStudio4data15TEOperationDataPCvUl
 */
void JStudio::TAdaptor::adaptor_setVariableValue(JStudio::TControl* pControl, u32 param_2,
                                                     JStudio::data::TEOperationData param_3,
                                                     void const* param_4, u32 param_5) {
    setVarFunc func;
    JUT_ASSERT(304, pControl!=0);
    switch (param_3) {
    case JStudio::data::UNK_0x1:
        func = &adaptor_setVariableValue_VOID_;
        break;
    case JStudio::data::UNK_0x2:
        func = &adaptor_setVariableValue_IMMEDIATE_;
        break;
    case JStudio::data::UNK_0x3:
        func = &adaptor_setVariableValue_TIME_;
        break;
    case JStudio::data::UNK_0x10:
        func = &adaptor_setVariableValue_FVR_NAME_;
        break;
    case JStudio::data::UNK_0x12:
        func = &adaptor_setVariableValue_FVR_INDEX_;
        break;
     default:
        return;
    }

    (*func)(this, pControl, param_2, param_4, param_5);
}


/* 802860CC-802861C0 280A0C 00F4+00 7/7 0/0 0/0 .text
 * adaptor_setVariableValue_n__Q27JStudio8TAdaptorFPQ27JStudio8TControlPCUlUlQ37JStudio4data15TEOperationDataPCvUl
 */
void JStudio::TAdaptor::adaptor_setVariableValue_n(JStudio::TControl* pControl,
                                                       u32 const* param_2, u32 param_3,
                                                       JStudio::data::TEOperationData param_4,
                                                       void const* param_5, u32 param_6) {
    JUT_ASSERT(343, pControl!=0);
    setVarFunc pcVar6;
    u32 iVar7;
    switch(param_4) {
    case JStudio::data::UNK_0x1:
        iVar7 = 0;
        pcVar6 = adaptor_setVariableValue_VOID_;
        break;
    case JStudio::data::UNK_0x2:
        iVar7 = 4;
        pcVar6 = adaptor_setVariableValue_IMMEDIATE_;
        break;
    case JStudio::data::UNK_0x3:
        iVar7 = 4;
        pcVar6 = adaptor_setVariableValue_TIME_;
        break;
    case JStudio::data::UNK_0x12:
        iVar7 = 4;
        pcVar6 = adaptor_setVariableValue_FVR_INDEX_;
        break;
    default:
        return;
    }
    
    JGadget::TEnumerator<const u32*> enumerator(param_2, param_2 + param_3);
    while (enumerator) {
        (*pcVar6)(this, pControl, **enumerator, param_5, iVar7);
        param_5 = (const void*)((int)param_5 + iVar7);
    }
}

/* 802861C0-80286204 280B00 0044+00 0/0 2/2 0/0 .text
 * adaptor_setVariableValue_immediate__Q27JStudio8TAdaptorFPCQ37JStudio8TAdaptor27TSetVariableValue_immediate
 */
void JStudio::TAdaptor::adaptor_setVariableValue_immediate(
    JStudio::TAdaptor::TSetVariableValue_immediate const* param_0) {
    u32 uVar1;
    while ((uVar1 = param_0->field_0x0) != 0xffffffff) {
        adaptor_setVariableValue_immediate(uVar1, param_0->field_0x4);
        param_0++;
    }
}

/* 80286204-80286274 280B44 0070+00 0/0 4/4 0/0 .text
 * adaptor_setVariableValue_Vec__Q27JStudio8TAdaptorFPCUlRC3Vec */
void JStudio::TAdaptor::adaptor_setVariableValue_Vec(u32 const* puIndex, Vec const& param_2) {
    JUT_ASSERT(400, puIndex!=0);
    adaptor_referVariableValue(puIndex[0])->setValue_immediate(param_2.x);
    adaptor_referVariableValue(puIndex[1])->setValue_immediate(param_2.y);
    adaptor_referVariableValue(puIndex[2])->setValue_immediate(param_2.z);
}

/* 80286274-802862AC 280BB4 0038+00 0/0 6/6 0/0 .text
 * adaptor_getVariableValue_Vec__Q27JStudio8TAdaptorCFP3VecPCUl */
void JStudio::TAdaptor::adaptor_getVariableValue_Vec(Vec* param_1, u32 const* param_2) const {
    param_1->x = adaptor_getVariableValue(param_2[0])->getValue();
    param_1->y = adaptor_getVariableValue(param_2[1])->getValue();
    param_1->z = adaptor_getVariableValue(param_2[2])->getValue();
}

/* 802862AC-8028638C 280BEC 00E0+00 0/0 3/3 0/0 .text
 * adaptor_setVariableValue_GXColor__Q27JStudio8TAdaptorFPCUlRC8_GXColor */
void JStudio::TAdaptor::adaptor_setVariableValue_GXColor(u32 const* puIndex,
                                                         GXColor const& param_2) {
    JUT_ASSERT(431, puIndex!=0);
    adaptor_referVariableValue(puIndex[0])->setValue_immediate(param_2.r);
    adaptor_referVariableValue(puIndex[1])->setValue_immediate(param_2.g);
    adaptor_referVariableValue(puIndex[2])->setValue_immediate(param_2.b);
    adaptor_referVariableValue(puIndex[3])->setValue_immediate(param_2.a);
}

/* 8028638C-802864D8 280CCC 014C+00 0/0 4/4 0/0 .text
 * adaptor_getVariableValue_GXColor__Q27JStudio8TAdaptorCFP8_GXColorPCUl */
void JStudio::TAdaptor::adaptor_getVariableValue_GXColor(GXColor* param_1,
                                                             u32 const* param_2) const {
    param_1->r = adaptor_getVariableValue(param_2[0])->getValue_uint8();
    param_1->g = adaptor_getVariableValue(param_2[1])->getValue_uint8();
    param_1->b = adaptor_getVariableValue(param_2[2])->getValue_uint8();
    param_1->a = adaptor_getVariableValue(param_2[3])->getValue_uint8();
}

/* 802864D8-8028656C 280E18 0094+00 1/1 0/0 0/0 .text
 * adaptor_updateVariableValue__Q27JStudio8TAdaptorFPQ27JStudio8TControlUl */
void JStudio::TAdaptor::adaptor_updateVariableValue(JStudio::TControl* pControl, u32 param_2) {
    JUT_ASSERT(479, pControl!=0);
    f64 dVar3 = pControl->getSecondPerFrame();
    JGadget::TEnumerator<JStudio::TVariableValue*> enumerator(pValue_, pValue_ + u);
    while (enumerator) {
        JStudio::TVariableValue* value = *enumerator;
        value->forward(param_2);
        value->update(dVar3, this);
    }
}

/* 8028656C-80286584 280EAC 0018+00 2/2 0/0 0/0 .text
 * adaptor_setVariableValue_VOID___Q27JStudio8TAdaptorFPQ27JStudio8TAdaptorPQ27JStudio8TControlUlPCvUl
 */
void JStudio::TAdaptor::adaptor_setVariableValue_VOID_(JStudio::TAdaptor* param_1,
                                                       JStudio::TControl* param_2, u32 param_3,
                                                       void const* param_4, u32 uSize) {
    JUT_ASSERT(499, uSize==0);
    param_1->pValue_[param_3].setValue_none();
}

/* 80286584-802865B0 280EC4 002C+00 2/2 0/0 0/0 .text
 * adaptor_setVariableValue_IMMEDIATE___Q27JStudio8TAdaptorFPQ27JStudio8TAdaptorPQ27JStudio8TControlUlPCvUl
 */
void JStudio::TAdaptor::adaptor_setVariableValue_IMMEDIATE_(JStudio::TAdaptor* param_1,
                                                            JStudio::TControl* param_2, u32 param_3,
                                                            void const* param_4, u32 param_5) {
    TVariableValue* value = &param_1->pValue_[param_3];
    value->setValue_immediate(*(f32*)param_4);
}

/* 802865B0-802865DC 280EF0 002C+00 2/2 0/0 0/0 .text
 * adaptor_setVariableValue_TIME___Q27JStudio8TAdaptorFPQ27JStudio8TAdaptorPQ27JStudio8TControlUlPCvUl
 */
void JStudio::TAdaptor::adaptor_setVariableValue_TIME_(JStudio::TAdaptor* param_1,
                                                       JStudio::TControl* param_2, u32 param_3,
                                                       void const* param_4, u32 param_5) {
    TVariableValue* value = &param_1->pValue_[param_3];
    value->setValue_time(*(f32*)param_4);
}

/* 802865DC-80286648 280F1C 006C+00 1/1 0/0 0/0 .text
 * adaptor_setVariableValue_FVR_NAME___Q27JStudio8TAdaptorFPQ27JStudio8TAdaptorPQ27JStudio8TControlUlPCvUl
 */
void JStudio::TAdaptor::adaptor_setVariableValue_FVR_NAME_(JStudio::TAdaptor* param_1,
                                                           JStudio::TControl* param_2, u32 param_3,
                                                           void const* param_4, u32 param_5) {
    TVariableValue* value = &param_1->pValue_[param_3];
    value->setValue_functionValue(param_2->getFunctionValue(param_4,param_5));
}

/* 80286648-802866B0 280F88 0068+00 2/2 0/0 0/0 .text
 * adaptor_setVariableValue_FVR_INDEX___Q27JStudio8TAdaptorFPQ27JStudio8TAdaptorPQ27JStudio8TControlUlPCvUl
 */
void JStudio::TAdaptor::adaptor_setVariableValue_FVR_INDEX_(JStudio::TAdaptor* param_1,
                                                            JStudio::TControl* param_2, u32 param_3,
                                                            void const* param_4, u32 param_5) {
    TVariableValue* value = &param_1->pValue_[param_3];
    value->setValue_functionValue(param_2->getFunctionValue_index(*(u32*)param_4));
}

/* 802866B0-80286734 280FF0 0084+00 8/8 0/0 0/0 .text            __dt__Q27JStudio7TObjectFv */
JStudio::TObject::~TObject() {
    delete mpAdaptor;
}

/* 80286734-8028679C 281074 0068+00 1/1 0/0 0/0 .text forward_value__Q27JStudio7TObjectFUl */
void JStudio::TObject::forward_value(u32 param_0) {
    TAdaptor* adaptor = getAdaptor();
    if (adaptor != NULL) {
        adaptor->adaptor_updateVariableValue(getControl(), param_0);
        adaptor->adaptor_do_update(param_0);
    }
}

/* 8028679C-802867D4 2810DC 0038+00 9/0 0/0 0/0 .text            do_begin__Q27JStudio7TObjectFv */
// NONMATCHING
void JStudio::TObject::do_begin() {
    TAdaptor* adaptor = getAdaptor();
    if (adaptor != NULL) {
        adaptor->adaptor_do_begin();
    }
}

/* 802867D4-8028680C 281114 0038+00 9/0 0/0 0/0 .text            do_end__Q27JStudio7TObjectFv */
void JStudio::TObject::do_end() {
    TAdaptor* adaptor = getAdaptor();
    if (adaptor != NULL) {
        adaptor->adaptor_do_end();
    }
}

/* 8028680C-8028682C 28114C 0020+00 9/0 0/0 0/0 .text            do_wait__Q27JStudio7TObjectFUl */
void JStudio::TObject::do_wait(u32 param_0) {
    forward_value(param_0);
}

/* 8028682C-80286864 28116C 0038+00 9/0 0/0 0/0 .text do_data__Q27JStudio7TObjectFPCvUlPCvUl */
void JStudio::TObject::do_data(void const* param_0, u32 param_1, void const* param_2,
                                   u32 param_3) {
    TAdaptor* adaptor = getAdaptor();
    if (adaptor != NULL) {
        adaptor->adaptor_do_data(param_0, param_1, param_2, param_3);
    }
}

/* 80286864-802868B0 2811A4 004C+00 8/8 0/0 0/0 .text
 * __ct__Q27JStudio7TObjectFRCQ47JStudio3stb4data20TParse_TBlock_objectPQ27JStudio8TAdaptor */
JStudio::TObject::TObject(JStudio::stb::data::TParse_TBlock_object const& param_0,
                          JStudio::TAdaptor* param_1)
    : stb::TObject(param_0), mpAdaptor(param_1) {}

/* 802868B0-80286910 2811F0 0060+00 0/0 1/1 0/0 .text            __dt__Q27JStudio14TAdaptor_actorFv
 */
// NONMATCHING
JStudio::TAdaptor_actor::~TAdaptor_actor() {
}

/* 80286910-8028694C 281250 003C+00 0/0 1/1 0/0 .text
 * __ct__Q27JStudio13TObject_actorFRCQ47JStudio3stb4data20TParse_TBlock_objectPQ27JStudio14TAdaptor_actor
 */
JStudio::TObject_actor::TObject_actor(JStudio::stb::data::TParse_TBlock_object const& param_0,
                                          JStudio::TAdaptor_actor* param_1) : TObject(param_0, param_1) {

}

/* 80431010-8043101C 05DD30 000C+00 3/3 0/0 0/0 .bss             @744 */
static u8 lit_744[12];

/* 8043101C-8043102C 05DD3C 0010+00 1/2 0/0 0/0 .bss
 * soovv_actor_PARENT_ENABLE___Q27JStudio28@unnamed@jstudio_object_cpp@ */
static u8 data_8043101C[16];

/* 8043102C-80431038 05DD4C 000C+00 0/1 0/0 0/0 .bss             @747 */
#pragma push
#pragma force_active on
static u8 lit_747[12];
#pragma pop

/* 80431038-80431048 05DD58 0010+00 1/2 0/0 0/0 .bss
 * soovv_actor_RELATION_ENABLE___Q27JStudio28@unnamed@jstudio_object_cpp@ */
static u8 data_80431038[16];

/* 804511F0-804511F8 0006F0 0004+04 6/6 6/6 0/0 .sbss soOutput_none___Q27JStudio14TVariableValue
 */
JStudio::TVariableValue::TOutput_none_ JStudio::TVariableValue::soOutput_none_;

/* 8028694C-80286C9C 28128C 0350+00 2/0 0/0 0/0 .text
 * do_paragraph__Q27JStudio13TObject_actorFUlPCvUl              */
void JStudio::TObject_actor::do_paragraph(u32 param_0, void const* param_1, u32 param_2) {
    // NONMATCHING
}

/* 80286C9C-80286CFC 2815DC 0060+00 0/0 1/1 0/0 .text __dt__Q27JStudio21TAdaptor_ambientLightFv */
// NONMATCHING
JStudio::TAdaptor_ambientLight::~TAdaptor_ambientLight() {}

/* 80286CFC-80286D38 28163C 003C+00 0/0 1/1 0/0 .text
 * __ct__Q27JStudio20TObject_ambientLightFRCQ47JStudio3stb4data20TParse_TBlock_objectPQ27JStudio21TAdaptor_ambientLight
 */
JStudio::TObject_ambientLight::TObject_ambientLight(
    JStudio::stb::data::TParse_TBlock_object const& param_0,
    JStudio::TAdaptor_ambientLight* param_1) : TObject(param_0, param_1) {
}

/* 80286D38-80286E1C 281678 00E4+00 1/0 0/0 0/0 .text
 * do_paragraph__Q27JStudio20TObject_ambientLightFUlPCvUl       */
void JStudio::TObject_ambientLight::do_paragraph(u32 param_0, void const* param_1,
                                                     u32 param_2) {
    // NONMATCHING
}

/* 80286E1C-80286E7C 28175C 0060+00 0/0 1/1 0/0 .text            __dt__Q27JStudio15TAdaptor_cameraFv
 */
// NONMATCHING
JStudio::TAdaptor_camera::~TAdaptor_camera() {}

/* 80286E7C-80286EB8 2817BC 003C+00 0/0 1/1 0/0 .text
 * __ct__Q27JStudio14TObject_cameraFRCQ47JStudio3stb4data20TParse_TBlock_objectPQ27JStudio15TAdaptor_camera
 */
JStudio::TObject_camera::TObject_camera(JStudio::stb::data::TParse_TBlock_object const& param_0,
                                        JStudio::TAdaptor_camera* param_1)
    : TObject(param_0, param_1) {}

/* 80431048-80431054 05DD68 000C+00 0/1 0/0 0/0 .bss             @750 */
#pragma push
#pragma force_active on
static u8 lit_750[12];
#pragma pop

/* 80431054-80431064 05DD74 0010+00 1/2 0/0 0/0 .bss
 * soovv_camera_PARENT_ENABLE___Q27JStudio28@unnamed@jstudio_object_cpp@ */
static u8 data_80431054[16];

/* 80431064-80431070 05DD84 000C+00 0/1 0/0 0/0 .bss             @753 */
#pragma push
#pragma force_active on
static u8 lit_753[12];
#pragma pop

/* 80431070-80431080 05DD90 0010+00 1/2 0/0 0/0 .bss
 * soovv_camera_TARGET_PARENT_ENABLE___Q27JStudio28@unnamed@jstudio_object_cpp@ */
static u8 data_80431070[16];

/* 80286EB8-8028717C 2817F8 02C4+00 2/0 0/0 0/0 .text
 * do_paragraph__Q27JStudio14TObject_cameraFUlPCvUl             */
void JStudio::TObject_camera::do_paragraph(u32 param_0, void const* param_1, u32 param_2) {
    // NONMATCHING
}

/* 8028717C-802871DC 281ABC 0060+00 0/0 1/1 0/0 .text            __dt__Q27JStudio12TAdaptor_fogFv */
// NONMATCHING
JStudio::TAdaptor_fog::~TAdaptor_fog() {}

/* 802871DC-80287218 281B1C 003C+00 0/0 1/1 0/0 .text
 * __ct__Q27JStudio11TObject_fogFRCQ47JStudio3stb4data20TParse_TBlock_objectPQ27JStudio12TAdaptor_fog
 */
JStudio::TObject_fog::TObject_fog(JStudio::stb::data::TParse_TBlock_object const& param_0,
                                      JStudio::TAdaptor_fog* param_1) : TObject(param_0, param_1) {}


/* 80287218-80287308 281B58 00F0+00 2/0 0/0 0/0 .text
 * do_paragraph__Q27JStudio11TObject_fogFUlPCvUl                */
void JStudio::TObject_fog::do_paragraph(u32 param_0, void const* param_1, u32 param_2) {
    // NONMATCHING
}

/* 80287308-80287368 281C48 0060+00 0/0 1/1 0/0 .text            __dt__Q27JStudio14TAdaptor_lightFv
 */
// NONMATCHING
JStudio::TAdaptor_light::~TAdaptor_light() {}

/* 80287368-802873A4 281CA8 003C+00 0/0 1/1 0/0 .text
 * __ct__Q27JStudio13TObject_lightFRCQ47JStudio3stb4data20TParse_TBlock_objectPQ27JStudio14TAdaptor_light
 */
JStudio::TObject_light::TObject_light(JStudio::stb::data::TParse_TBlock_object const& param_0,
                                          JStudio::TAdaptor_light* param_1) : TObject(param_0, param_1) {}

/* 802873A4-802875E0 281CE4 023C+00 2/0 0/0 0/0 .text
 * do_paragraph__Q27JStudio13TObject_lightFUlPCvUl              */
void JStudio::TObject_light::do_paragraph(u32 param_0, void const* param_1, u32 param_2) {
    // NONMATCHING
}

/* 802875E0-80287640 281F20 0060+00 0/0 1/1 0/0 .text __dt__Q27JStudio16TAdaptor_messageFv */
JStudio::TAdaptor_message::~TAdaptor_message() {}

/* 80287640-8028767C 281F80 003C+00 0/0 1/1 0/0 .text
 * __ct__Q27JStudio15TObject_messageFRCQ47JStudio3stb4data20TParse_TBlock_objectPQ27JStudio16TAdaptor_message
 */
JStudio::TObject_message::TObject_message(JStudio::stb::data::TParse_TBlock_object const& param_0,
                                          JStudio::TAdaptor_message* param_1)
    : TObject(param_0, param_1) {}

/* 8028767C-8028770C 281FBC 0090+00 1/0 0/0 0/0 .text
 * do_paragraph__Q27JStudio15TObject_messageFUlPCvUl            */
// NONMATCHING - param_1 &= 0x1f is out of place + unsure about the pmfn
void JStudio::TObject_message::do_paragraph(u32 param_1, void const* param_2, u32 param_3) {
    TAdaptor* adaptor = getAdaptor();
    if (adaptor != NULL) {
        u32 uVar1 = (param_1 >> 5);
        param_1 &= 0x1f;
        paragraphFunc pmfn_ = NULL;
        switch (uVar1) {
        case 0x42:
            pmfn_ = &TObject::do_paragraph;
            JUT_ASSERT(1161, pmfn_!=0);
            break;
        default:
            return;
        }
        (((TObject*)adaptor)->*pmfn_)(param_1, param_2, param_3);
    }

}

/* 8028770C-8028776C 28204C 0060+00 0/0 1/1 0/0 .text __dt__Q27JStudio17TAdaptor_particleFv */
// NONMATCHING
JStudio::TAdaptor_particle::~TAdaptor_particle() {}

/* 8028776C-802877A8 2820AC 003C+00 0/0 1/1 0/0 .text
 * __ct__Q27JStudio16TObject_particleFRCQ47JStudio3stb4data20TParse_TBlock_objectPQ27JStudio17TAdaptor_particle
 */
JStudio::TObject_particle::TObject_particle(
    JStudio::stb::data::TParse_TBlock_object const& param_0, JStudio::TAdaptor_particle* param_1) : TObject(param_0, param_1) {}

/* 802877A8-80287B3C 2820E8 0394+00 2/0 0/0 0/0 .text
 * do_paragraph__Q27JStudio16TObject_particleFUlPCvUl           */
void JStudio::TObject_particle::do_paragraph(u32 param_0, void const* param_1, u32 param_2) {
    // NONMATCHING
}

/* 80287B3C-80287B9C 28247C 0060+00 0/0 1/1 0/0 .text            __dt__Q27JStudio14TAdaptor_soundFv
 */
// NONMATCHING
JStudio::TAdaptor_sound::~TAdaptor_sound() {}

/* 80287B9C-80287BD8 2824DC 003C+00 0/0 1/1 0/0 .text
 * __ct__Q27JStudio13TObject_soundFRCQ47JStudio3stb4data20TParse_TBlock_objectPQ27JStudio14TAdaptor_sound
 */
JStudio::TObject_sound::TObject_sound(JStudio::stb::data::TParse_TBlock_object const& param_0,
                                          JStudio::TAdaptor_sound* param_1) : TObject(param_0, param_1) {}

/* 80287BD8-80287F04 282518 032C+00 2/0 0/0 0/0 .text
 * do_paragraph__Q27JStudio13TObject_soundFUlPCvUl              */
void JStudio::TObject_sound::do_paragraph(u32 param_0, void const* param_1, u32 param_2) {
    // NONMATCHING
}

/* 80287F04-80287F64 282844 0060+00 1/0 0/0 0/0 .text            __dt__Q27JStudio13TObject_soundFv
 */
// JStudio::TObject_sound::~TObject_sound() {
extern "C" void __dt__Q27JStudio13TObject_soundFv() {
    // NONMATCHING
}

/* 80287F64-80287FC4 2828A4 0060+00 1/0 0/0 0/0 .text __dt__Q27JStudio16TObject_particleFv */
// JStudio::TObject_particle::~TObject_particle() {
extern "C" void __dt__Q27JStudio16TObject_particleFv() {
    // NONMATCHING
}

/* 80287FC4-80288024 282904 0060+00 1/0 0/0 0/0 .text            __dt__Q27JStudio15TObject_messageFv
 */
// JStudio::TObject_message::~TObject_message() {
extern "C" void __dt__Q27JStudio15TObject_messageFv() {
    // NONMATCHING
}

/* 80288024-80288084 282964 0060+00 1/0 0/0 0/0 .text            __dt__Q27JStudio13TObject_lightFv
 */
// JStudio::TObject_light::~TObject_light() {
extern "C" void __dt__Q27JStudio13TObject_lightFv() {
    // NONMATCHING
}

/* 80288084-802880E4 2829C4 0060+00 1/0 0/0 0/0 .text            __dt__Q27JStudio11TObject_fogFv */
// JStudio::TObject_fog::~TObject_fog() {
extern "C" void __dt__Q27JStudio11TObject_fogFv() {
    // NONMATCHING
}

/* 802880E4-80288144 282A24 0060+00 1/0 0/0 0/0 .text            __dt__Q27JStudio14TObject_cameraFv
 */
// JStudio::TObject_camera::~TObject_camera() {
extern "C" void __dt__Q27JStudio14TObject_cameraFv() {
    // NONMATCHING
}

/* 80288144-802881A4 282A84 0060+00 1/0 0/0 0/0 .text __dt__Q27JStudio20TObject_ambientLightFv */
// JStudio::TObject_ambientLight::~TObject_ambientLight() {
extern "C" void __dt__Q27JStudio20TObject_ambientLightFv() {
    // NONMATCHING
}

/* 802881A4-80288204 282AE4 0060+00 1/0 0/0 0/0 .text            __dt__Q27JStudio13TObject_actorFv
 */
// JStudio::TObject_actor::~TObject_actor() {
extern "C" void __dt__Q27JStudio13TObject_actorFv() {
    // NONMATCHING
}
